### ISSUE TITLE
Special characters in IDs result in invalid output

### ISSUE THREAD

**Issue by MingweiSamuel** [besok/graphviz-rust#3]
Example:
```rust
let graph = {
    use graphviz_rust::dot_generator::*;
    graph!(strict di id!("h[t]"))
};

let mut ctx = PrinterContext::default();
ctx.with_indent_step(2);
let out = graph.print(&mut ctx);
```

Output (invalid DOT):
```dot
strict digraph h[t] {

}
```

Expected output:
```dot
strict digraph "h[t]" {

}
```

**Comment by besok** [comment]
Agree.

**Comment by besok** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [graphviz id](https://trello.com/c/BLVI2e5A/723-graphviz-id)

**Comment by besok** [comment]
Since we don't parse the incoming string in the macros, there is no way to distinguish whether the string should be with quotes or not.
But the macro provides the way to wrap the string with quotes by using esc prefix, namely:
```rust
let graph = {
    use graphviz_rust::dot_generator::*;
    graph!(strict di id!(esc "h[t]"))
};
let out = graph.print( PrinterContext::default().with_indent_step(2));
```

And in the case above, since we know the name includes the forbidden symbols, we can handle it with the escaped string.
