### ISSUE TITLE
Add Clone/Copy impls for enum cmd::Format, export a version of exec that takes a rendered graph, add more descriptive error messages

### ISSUE THREAD

**Issue by dreamsmasher** [besok/graphviz-rust#9]
Hi, I'm currently using graphviz-rust to build some dependency graph visualizations and I've run into some small issues with the API that mildly affect UX.

1. No way to clone a `cmd::Format`.
`cmd::Format` doesn't implement Clone, so there's no way to set constants for default layouts, or take a desired layout as a command-line argument. It seems that it should be possible to derive `Clone` on this type given that it's a simple enum.

2. No way to cache the result of `print`ing a `Graph` before passing it to `exec`.
I'm currently building a `Graph` then rendering it to svg, but I'd like to export the rendered .dot file as well. The `exec` function exported from the crate root only takes a `Graph` as an argument, but runs `print` on it immediately. There's no way to reuse the result of `print` and pass it directly to `exec` afterward - this results in the graph needing to be `print`ed twice in order to both save the raw `.dot` markup and call graphviz on it. It would be nice to have a similar function, e.g. `exec_from_dot_file`, that takes a string as input.

3. Nondescriptive error message when graphviz is missing from PATH
If the user doesn't have `dot` in their PATH, `exec` fails with an error `No file or directory found`. It isn't immediately obvious what the source of this error is, or how to remedy it. `exec` should ideally return a message telling the user to install `graphviz`; this caveat is mentioned in the docs but buried inside the `cmd` module.

Thank you for releasing this crate, it's super useful!

**Comment by besok** [comment]
Hi,
Sure thing. Will take a look shortly(this week).

**Comment by besok** [comment]
Hi,
Have provided an mr covering all aforesaid causes.

1. Added clone, copy
2. Added method exec_dot that accepts a graph in a string format
3. As for the error. This is a little bit moot thing. The message and behaviour in general can be different depending on the client and the operating system that is used. Thus, I don't see a quick solution that standardizes a way to recognize(since we just float up the message from the console). For now, I am inclined to stick with expanding the section in the readme file and adding a message there, basing on the fact  that  the error can occur once

**Comment by dreamsmasher** [comment]
Thank you!
